# Generated by Django 3.2.8 on 2024-12-02 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TallerMantenimiento',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='ID del Taller')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Taller')),
                ('estado_registro', models.CharField(choices=[('eléctrico', 'Eléctrico'), ('mecánico', 'Mecánico'), ('pintura', 'Pintura'), ('automotriz', 'Automotriz')], max_length=20, verbose_name='Estado de Registro')),
            ],
            options={
                'verbose_name': 'Taller de Mantenimiento',
                'verbose_name_plural': 'Talleres de Mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='ID del Tipo de Equipo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Tipo de Equipo')),
                ('estado_registro', models.CharField(choices=[('eléctrico', 'Eléctrico'), ('mecánico', 'Mecánico'), ('mecatrónico', 'Mecatrónico')], max_length=20, verbose_name='Estado de Registro')),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipos de Equipos',
            },
        ),
        migrations.CreateModel(
            name='MaestroEquipo',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='ID del Equipo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('estado_registro', models.BooleanField(default=True, verbose_name='Estado de Registro')),
                ('taller_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='maestro.tallermantenimiento', verbose_name='Taller de Mantenimiento')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='maestro.tipoequipo', verbose_name='Tipo de Equipo')),
            ],
            options={
                'verbose_name': 'Maestro de Equipo',
                'verbose_name_plural': 'Maestros de Equipos',
            },
        ),
    ]
