# Generated by Django 3.2.8 on 2024-12-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tallermantenimiento',
            name='tipo_taller',
        ),
        migrations.RemoveField(
            model_name='tipoequipo',
            name='tipo_equipo',
        ),
    ]
