# Generated by Django 3.2.8 on 2024-12-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maestroequipo',
            options={'ordering': ['nombre'], 'verbose_name': 'Maestro de Equipo', 'verbose_name_plural': 'Maestros de Equipos'},
        ),
        migrations.AlterField(
            model_name='maestroequipo',
            name='estado_registro',
            field=models.BooleanField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('*', 'Eliminado')], default='A', max_length=1, verbose_name='Estado de Registro'),
        ),
    ]
