# Generated by Django 3.2.8 on 2024-12-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0002_auto_20241203_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestroequipo',
            name='estado_registro',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('*', 'Eliminado')], default='A', max_length=1, verbose_name='Estado de Registro'),
        ),
    ]
