# Generated by Django 3.2.8 on 2024-12-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestro', '0002_auto_20241204_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestroequipo',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='ID del Equipo'),
        ),
        migrations.AlterField(
            model_name='tallermantenimiento',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='ID del Taller'),
        ),
        migrations.AlterField(
            model_name='tipoequipo',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='ID del Tipo de Equipo'),
        ),
    ]
